# Generated by Django 6.0.1 on 2026-01-07 12:18

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("complaints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_number",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("created", "Created"),
                            ("pending_approval", "Pending Superior Approval"),
                            ("investigation", "Under Investigation"),
                            ("suspect_identified", "Suspect Identified"),
                            ("interrogation", "Interrogation"),
                            ("pending_captain", "Pending Captain Decision"),
                            ("pending_chief", "Pending Chief Decision (Critical)"),
                            ("trial", "In Trial"),
                            ("closed_solved", "Closed - Solved"),
                            ("closed_unsolved", "Closed - Unsolved"),
                        ],
                        default="created",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("complaint", "From Complaint"),
                            ("crime_scene", "From Crime Scene Report"),
                        ],
                        default="complaint",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "crime_severity",
                    models.IntegerField(
                        choices=[
                            (3, "Level 3 - Minor (petty theft, minor fraud)"),
                            (2, "Level 2 - Major (car theft)"),
                            (1, "Level 1 - Severe (murder)"),
                            (0, "Critical (serial murder, terrorism)"),
                        ],
                        default=3,
                    ),
                ),
                ("crime_scene_time", models.DateTimeField(blank=True, null=True)),
                ("crime_scene_location", models.CharField(blank=True, max_length=255)),
                (
                    "detective_board",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detective board layout data (positions, connections)",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Superior who approved crime scene case",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_detective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "officers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cases_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_complaint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_create_from_crime_scene", "Can create case from crime scene"),
                    ("can_approve_case", "Can approve cases"),
                    ("can_assign_detective", "Can assign detective to case"),
                    ("can_identify_suspect", "Can identify suspects"),
                    ("can_close_case", "Can close cases"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending_approval", "Pending Superior Approval"),
                            ("investigation", "Under Investigation"),
                            ("suspect_identified", "Suspect Identified"),
                            ("interrogation", "Interrogation"),
                            ("pending_captain", "Pending Captain Decision"),
                            ("pending_chief", "Pending Chief Decision (Critical)"),
                            ("trial", "In Trial"),
                            ("closed_solved", "Closed - Solved"),
                            ("closed_unsolved", "Closed - Unsolved"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending_approval", "Pending Superior Approval"),
                            ("investigation", "Under Investigation"),
                            ("suspect_identified", "Suspect Identified"),
                            ("interrogation", "Interrogation"),
                            ("pending_captain", "Pending Captain Decision"),
                            ("pending_chief", "Pending Chief Decision (Critical)"),
                            ("trial", "In Trial"),
                            ("closed_solved", "Closed - Solved"),
                            ("closed_unsolved", "Closed - Unsolved"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="cases.case",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Case histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrimeSceneWitness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("national_id", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witnesses",
                        to="cases.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="witness_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Crime scene witnesses",
            },
        ),
    ]
