# Generated by Django 6.0.1 on 2026-01-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("suspects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_data",
                    models.JSONField(default=dict, help_text="Full case report data"),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judicial_report",
                        to="cases.case",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_date", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("guilty", "Guilty"),
                            ("not_guilty", "Not Guilty"),
                            ("dismissed", "Case Dismissed"),
                            ("mistrial", "Mistrial"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("verdict_date", models.DateTimeField(blank=True, null=True)),
                ("verdict_notes", models.TextField(blank=True)),
                ("court_name", models.CharField(blank=True, max_length=255)),
                ("court_room", models.CharField(blank=True, max_length=50)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial",
                        to="cases.case",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials_presided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
                "permissions": [
                    ("can_preside_trial", "Can preside over trials"),
                    ("can_issue_verdict", "Can issue verdicts"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Type of sentence (imprisonment, fine, etc.)",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(help_text="Full sentence details")),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Sentence duration in days", null=True
                    ),
                ),
                (
                    "fine_amount",
                    models.PositiveIntegerField(
                        blank=True, help_text="Fine amount in Rials", null=True
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sentences_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="suspects.suspect",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="judiciary.trial",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
