# Generated by Django 6.0.1 on 2026-01-07 12:18

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Suspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("identified", "Identified"),
                            ("under_investigation", "Under Investigation"),
                            ("under_pursuit", "Under Pursuit (Wanted)"),
                            ("most_wanted", "Most Wanted"),
                            ("arrested", "Arrested"),
                            ("cleared", "Cleared"),
                            ("convicted", "Convicted"),
                        ],
                        default="identified",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("aliases", models.CharField(blank=True, max_length=500)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="suspects/"),
                ),
                ("description", models.TextField(blank=True)),
                ("wanted_since", models.DateTimeField(blank=True, null=True)),
                ("arrested_at", models.DateTimeField(blank=True, null=True)),
                ("last_known_location", models.CharField(blank=True, max_length=255)),
                (
                    "detective_guilt_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Detective's guilt probability score (1-10)",
                        null=True,
                    ),
                ),
                (
                    "sergeant_guilt_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Sergeant's guilt probability score (1-10)",
                        null=True,
                    ),
                ),
                (
                    "captain_decision",
                    models.TextField(
                        blank=True, help_text="Captain's final decision notes"
                    ),
                ),
                (
                    "chief_decision",
                    models.TextField(
                        blank=True, help_text="Chief's decision for critical cases"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspect_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interrogation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("transcription", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interrogations",
                        to="cases.case",
                    ),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interrogations_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interrogations",
                        to="suspects.suspect",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseSuspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Suspect"),
                            ("accomplice", "Accomplice"),
                            ("witness_turned", "Witness Turned Suspect"),
                            ("poi", "Person of Interest"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspect_links",
                        to="cases.case",
                    ),
                ),
                (
                    "suspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_links",
                        to="suspects.suspect",
                    ),
                ),
            ],
            options={
                "unique_together": {("case", "suspect")},
            },
        ),
    ]
