# Generated by Django 5.2.11 on 2026-02-27 00:51

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='status',
            field=django_fsm.FSMField(choices=[('identified', 'Identified'), ('under_investigation', 'Under Investigation'), ('under_pursuit', 'Under Pursuit (Wanted)'), ('most_wanted', 'Most Wanted'), ('arrested', 'Arrested'), ('released_on_bail', 'Released on Bail'), ('cleared', 'Cleared'), ('convicted', 'Convicted')], default='identified', max_length=50, protected=True),
        ),
    ]
