# Generated by Django 6.0.1 on 2026-01-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("suspects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("officer_review", "Under Officer Review"),
                            ("officer_rejected", "Rejected by Officer"),
                            ("detective_review", "Under Detective Review"),
                            ("detective_rejected", "Rejected by Detective"),
                            ("approved", "Approved"),
                            ("reward_claimed", "Reward Claimed"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("officer_review_date", models.DateTimeField(blank=True, null=True)),
                ("officer_notes", models.TextField(blank=True)),
                ("detective_review_date", models.DateTimeField(blank=True, null=True)),
                ("detective_notes", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips",
                        to="cases.case",
                    ),
                ),
                (
                    "reviewed_by_detective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tips_reviewed_as_detective",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tips_reviewed_as_officer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tips_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips",
                        to="suspects.suspect",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(editable=False, max_length=36, unique=True)),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="Reward amount in Rials"),
                ),
                ("is_claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimed_by_officer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Officer who processed the reward claim",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewards_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_code",
                        to="rewards.tip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
