# Generated by Django 5.2.11 on 2026-02-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.TextField(),
        ),
    ]
