# Generated by Django 5.2.11 on 2026-02-27 00:51

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_national_id_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
