# Generated by Django 6.0.1 on 2026-01-07 12:18

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted by Complainant"),
                            ("cadet_review", "Under Cadet Review"),
                            ("returned", "Returned to Complainant"),
                            ("officer_review", "Under Officer Review"),
                            ("returned_to_cadet", "Returned to Cadet"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("invalidated", "Invalidated (3 strikes)"),
                        ],
                        default="draft",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("incident_date", models.DateTimeField(blank=True, null=True)),
                (
                    "crime_severity",
                    models.IntegerField(
                        choices=[
                            (3, "Level 3 - Minor (petty theft, minor fraud)"),
                            (2, "Level 2 - Major (car theft)"),
                            (1, "Level 1 - Severe (murder)"),
                            (0, "Critical (serial murder, terrorism)"),
                        ],
                        default=3,
                    ),
                ),
                ("rejection_count", models.PositiveSmallIntegerField(default=0)),
                ("last_rejection_message", models.TextField(blank=True)),
                (
                    "assigned_cadet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_as_cadet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_as_officer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complainants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="complaints_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_submit_complaint", "Can submit complaint"),
                    ("can_review_as_cadet", "Can review complaints as cadet"),
                    ("can_review_as_officer", "Can review complaints as officer"),
                    ("can_approve_complaint", "Can approve complaints"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplaintHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted by Complainant"),
                            ("cadet_review", "Under Cadet Review"),
                            ("returned", "Returned to Complainant"),
                            ("officer_review", "Under Officer Review"),
                            ("returned_to_cadet", "Returned to Cadet"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("invalidated", "Invalidated (3 strikes)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted by Complainant"),
                            ("cadet_review", "Under Cadet Review"),
                            ("returned", "Returned to Complainant"),
                            ("officer_review", "Under Officer Review"),
                            ("returned_to_cadet", "Returned to Cadet"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("invalidated", "Invalidated (3 strikes)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Complaint histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
